### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by bruel-gabrielsson** [afiaka87/dalle-pytorch-datasets#2]
Afiaka87, can I please have your email? Thanks!

**Comment by afiaka87** [comment]
> Afiaka87, can I please have your email? Thanks!

Probably not an issue - I use a pseudonym on GitHub however.

What's the topic of discussion?

**Comment by bruel-gabrielsson** [comment]
An opportunity for collaboration!

**Comment by afiaka87** [comment]
claymullis+gh@fastmail.com
